### ISSUE TITLE
`OnOnDestroy`, `OnOnEnable`, `OnOnDisable`, etc.

### ISSUE THREAD

**Issue by willis81808** [pdcook/ModdingUtils#14]
Naming convention here is awkward. I suggest releasing a new major version (because it would be a breaking change) where these are entirely removed, and the base unity MonoBehaviour events are flagged as virtual instead.

For example:
```cs
public void Awake()
{
    // do stuff

    OnAwake();
}
public virtual void OnAwake() { }
```
Should just be be:
```cs
public virtual void Awake()
{
    // do stuff
}
```

Usage would be:
```cs
// Like this
public override void Awake()
{
    base.Awake();
    // do stuff
}

// Instead of this
public override void OnAwake()
{
    // do stuff
}
```

**Comment by pdcook** [comment]
According to people in the Unity discord server, marking the `Monobehaviour` methods as `public` can cause undefined behavior and/or unintended consequences. I had asked them about exactly this when I was making `ReversibleEffects`.

I have never seen these issues they warn of, but I wasn't and still am not, a Unity expert.

**Comment by willis81808** [comment]
Whoever said that is crazy 👅 

Even if that was the case, it would just mean use `protected`  instead of `public` or `private`.
